export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SET_USERS_LISTS: "SET_USERS_LISTS",
  REMOVE_USERS_LISTS: "REMOVE_USERS_LISTS",
};
